spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/talent?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 100MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
#    path: D:/DeskTop/java-demo/sping-admin/files/
    path: D:/DeskTop/files/